service: hello-sls

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stackName: ${sls:stage}-hello-sls
  apiName: ${sls:stage}-hello-sls

functions:
  hello:
    name: ${sls:stage}-hello-sls
    handler: app/handler.hello
    events:
      - http:
          path: hello
          method: get
